//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelFirstFahrzeuge
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fahrzeuge
    {
        public int Id { get; set; }
        public int Marke { get; set; }
        public System.DateTime Erstzulassung { get; set; }
        public short PS { get; set; }
        public string Farbe { get; set; }
    
        public virtual Marke Marke1 { get; set; }
    }
}
